### ISSUE TITLE
Error when creating a content to display

### ISSUE THREAD

**Issue by minapok** [cedricziel/jfmulticontent#6]
When creating a new multiple content element with the view "Contents" the user has several possibilities to select the contents which should be displayed: selecting existing content records or create a new content record.
By chosing option "Create new record" and saving this new record an error message is shown in the backend:

`1: Attempt to insert record on page '[root-level]' (0) where this table, tt_content, is not allowed`

In previous versions a general record storage had to be set in the page settings, but this was removed in TYPO3 CMS 7.4.

Tested with a blank TYPO3 CMS 7.6.15-dev. The view "Inline content" works.

**Comment by cedricziel** [comment]
Hi @frau-liessmann,

thx for the report-we don't actively use this package and the fork was only made for a transitioning-phase. I suggest you move to a new solution.

Thx.
